In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/bank_transactions.csv')

In [3]:
df.head()

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount (INR)
0,T1,C5841053,10/1/94,F,JAMSHEDPUR,17819.05,2/8/16,143207,25.0
1,T2,C2142763,4/4/57,M,JHAJJAR,2270.69,2/8/16,141858,27999.0
2,T3,C4417068,26/11/96,F,MUMBAI,17874.44,2/8/16,142712,459.0
3,T4,C5342380,14/9/73,F,MUMBAI,866503.21,2/8/16,142714,2060.0
4,T5,C9031234,24/3/88,F,NAVI MUMBAI,6714.43,2/8/16,181156,1762.5

In [4]:
df.shape

(1048567, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048567 entries, 0 to 1048566
Data columns (total 9 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   TransactionID            1048567 non-null  object
 1   CustomerID               1048567 non-null  object
 2   CustomerDOB              1045170 non-null  object
 3   CustGender               1047467 non-null  object
 4   CustLocation             1048416 non-null  object
 5   CustAccountBalance       1046198 non-null  float64
 6   TransactionDate          1048567 non-null  object
 7   TransactionTime          1048567 non-null  int64
 8   TransactionAmount (INR)  1048567 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 72.0+ MB

In [6]:
df.isnull().sum()

TransactionID                 0
CustomerID                    0
CustomerDOB                3397
CustGender                 1100
CustLocation                151
CustAccountBalance         2369
TransactionDate               0
TransactionTime               0
TransactionAmount (INR)       0
dtype: int64

In [7]:
(df.isnull().sum()/len(df)) * 100

TransactionID              0.000000
CustomerID                 0.000000
CustomerDOB                0.323966
CustGender                 0.104905
CustLocation               0.014401
CustAccountBalance         0.225927
TransactionDate            0.000000
TransactionTime            0.000000
TransactionAmount (INR)    0.000000
dtype: float64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
(df.isnull().sum() / len(df) * 100).round(2)

TransactionID              0.00
CustomerID                 0.00
CustomerDOB                0.32
CustGender                 0.10
CustLocation               0.01
CustAccountBalance         0.23
TransactionDate            0.00
TransactionTime            0.00
TransactionAmount (INR)    0.00
dtype: float64

In [10]:
df.nunique()

TransactionID              1048567
CustomerID                  884265
CustomerDOB                  17254
CustGender                       3
CustLocation                  9355
CustAccountBalance          161328
TransactionDate                 55
TransactionTime              81918
TransactionAmount (INR)      93024
dtype: int64

In [11]:
df['TransactionID'].duplicated().sum()

np.int64(0)

In [12]:
df['CustomerID'].duplicated().sum()

np.int64(164302)

In [13]:
df['CustGender'].value_counts(dropna=False)

CustGender
M      765530
F      281936
NaN      1100
T           1
Name: count, dtype: int64

In [14]:
df['CustomerDOB'].head(10)

0     10/1/94
1      4/4/57
2    26/11/96
3     14/9/73
4     24/3/88
5     8/10/72
6     26/1/92
7     27/1/82
8     19/4/88
9     22/6/84
Name: CustomerDOB, dtype: object

In [15]:
df['TransactionDate'].head(10)

0    2/8/16
1    2/8/16
2    2/8/16
3    2/8/16
4    2/8/16
5    2/8/16
6    2/8/16
7    2/8/16
8    2/8/16
9    2/8/16
Name: TransactionDate, dtype: object

In [16]:
df[['CustAccountBalance', 'TransactionAmount (INR)']].describe()

       CustAccountBalance  TransactionAmount (INR)
count        1.046198e+06             1.048567e+06
mean         1.154035e+05             1.574335e+03
std          8.464854e+05             6.574743e+03
min          0.000000e+00             0.000000e+00
25%          4.721760e+03             1.610000e+02
50%          1.679218e+04             4.590300e+02
75%          5.765736e+04             1.200000e+03
max          1.150355e+08             1.560035e+06

In [17]:
df['CustomerDOB'].value_counts().head(20)

CustomerDOB
1/1/1800    57339
1/1/89        809
1/1/90        784
6/8/91        699
1/1/91        666
1/1/92        633
1/7/90        619
21/11/86      602
1/1/87        601
1/1/88        592
1/1/93        527
1/6/90        467
1/7/92        462
1/7/89        460
1/6/92        440
1/1/85        439
1/1/86        436
1/7/84        435
10/10/91      424
1/1/83        415
Name: count, dtype: int64

In [18]:
df['CustomerDOB'].value_counts().tail(20)

CustomerDOB
5/8/41      1
1/6/45      1
25/5/01     1
23/7/53     1
27/2/66     1
29/4/61     1
3/12/43     1
23/11/30    1
28/9/48     1
6/9/43      1
11/2/48     1
13/7/58     1
5/5/57      1
20/8/62     1
28/2/99     1
24/12/58    1
25/6/52     1
6/6/42      1
6/1/40      1
26/4/64     1
Name: count, dtype: int64

In [20]:
df[df['CustGender'] == 'T']

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount (INR)
959987,T959988,C3380368,1/1/1800,T,CHENNAI,50050.0,10/9/16,170731,32500.0

In [30]:
dob_1800 = df[df['CustomerDOB'].str.contains('1800', na=False)]

In [32]:
dob_1800['CustomerDOB'].value_counts()

CustomerDOB
1/1/1800    57339
Name: count, dtype: int64

In [35]:
df['CustomerDOB'].str[-2:].value_counts().sort_index()

CustomerDOB
00    57608
01      142
02      141
03       69
04       75
      ...
95    20756
96    12518
97     7163
98     1952
99      688
Name: count, Length: 99, dtype: int64

In [36]:
import numpy as np

In [37]:
df['CustomerDOB'] = df['CustomerDOB'].replace('1/1/1800', np.nan)

In [38]:
df['CustomerDOB'].value_counts().head()

CustomerDOB
1/1/89    809
1/1/90    784
6/8/91    699
1/1/91    666
1/1/92    633
Name: count, dtype: int64

In [39]:
df['CustomerDOB'].isnull().sum()

np.int64(60736)

In [51]:
dob_parsed = pd.to_datetime(
    df['CustomerDOB'],
    format='%d/%m/%y',
    errors='coerce'
)

In [52]:
dob_parsed.head(10)

0   1994-01-10
1   2057-04-04
2   1996-11-26
3   1973-09-14
4   1988-03-24
5   1972-10-08
6   1992-01-26
7   1982-01-27
8   1988-04-19
9   1984-06-22
Name: CustomerDOB, dtype: datetime64[ns]

In [53]:
dob_parsed.dt.year.value_counts().sort_index()

CustomerDOB
1969.0    5965
1970.0    7283
1971.0    7420
1972.0    9221
1973.0    9957
          ...
2064.0    3582
2065.0    3894
2066.0    4202
2067.0    4459
2068.0    5903
Name: count, Length: 99, dtype: int64

In [54]:
future_dob = dob_parsed.dt.year > 2016
future_dob

0          False
1           True
2          False
3          False
4          False
           ...
1048562    False
1048563    False
1048564    False
1048565    False
1048566    False
Name: CustomerDOB, Length: 1048567, dtype: bool

In [55]:
future_dob.sum()

np.int64(54427)

In [56]:
dob_parsed.loc[future_dob] = dob_parsed.loc[future_dob] - pd.DateOffset(years=100)
dob_parsed.loc[future_dob]

1         1957-04-04
15        1968-07-10
30        1967-01-21
51        1966-07-25
79        1967-05-25
             ...
1048495   1962-09-01
1048496   1967-05-07
1048500   1951-07-01
1048510   1948-07-15
1048536   1933-10-05
Name: CustomerDOB, Length: 54427, dtype: datetime64[ns]

In [59]:
dob_parsed.head(10)

0   1994-01-10
1   1957-04-04
2   1996-11-26
3   1973-09-14
4   1988-03-24
5   1972-10-08
6   1992-01-26
7   1982-01-27
8   1988-04-19
9   1984-06-22
Name: CustomerDOB, dtype: datetime64[ns]

In [57]:
dob_parsed.dt.year.min()

1918.0

In [58]:
dob_parsed.dt.year.max()

2016.0

In [60]:
transaction_date_parsed = pd.to_datetime(
    df['TransactionDate'],
    format='%d/%m/%y',
    errors='coerce'
)

In [61]:
transaction_date_parsed.head()

0   2016-08-02
1   2016-08-02
2   2016-08-02
3   2016-08-02
4   2016-08-02
Name: TransactionDate, dtype: datetime64[ns]

In [62]:
transaction_date_parsed.min()

Timestamp('2016-08-01 00:00:00')

In [63]:
transaction_date_parsed.max()

Timestamp('2016-10-21 00:00:00')

In [64]:
age = transaction_date_parsed.dt.year - dob_parsed.dt.year

In [65]:
age.describe()

count    987831.000000
mean         31.034427
std           8.768935
min           0.000000
25%          25.000000
50%          29.000000
75%          34.000000
max          98.000000
dtype: float64

In [66]:
(age < 18).sum()

np.int64(1639)

In [67]:
age.value_counts().sort_index().head(25)

0.0         2
1.0        25
2.0        10
3.0        27
4.0        28
5.0         2
6.0        18
7.0        17
8.0        16
9.0        46
10.0       21
11.0       43
12.0       75
13.0       69
14.0      141
15.0      142
16.0      269
17.0      688
18.0     1952
19.0     7163
20.0    12518
21.0    20756
22.0    36286
23.0    53277
24.0    66708
Name: count, dtype: int64

In [68]:
age.min()

0.0

In [69]:
age.max()

98.0

In [70]:
age = (
    transaction_date_parsed.dt.year
    - dob_parsed.dt.year
    - (
        (transaction_date_parsed.dt.month < dob_parsed.dt.month) |
        (
            (transaction_date_parsed.dt.month == dob_parsed.dt.month)
             &
            (transaction_date_parsed.dt.day < dob_parsed.dt.day)
        )
    )
)

In [71]:
age.describe()

count    987831.000000
mean         30.695170
std           8.776681
min           0.000000
25%          25.000000
50%          28.000000
75%          34.000000
max          98.000000
dtype: float64

In [72]:
(age < 18).sum()

np.int64(1980)

In [73]:
age.value_counts().sort_index().head(20)

0.0        6
1.0       23
2.0       19
3.0       18
4.0       28
5.0       16
6.0       13
7.0       10
8.0       19
9.0       40
10.0      32
11.0      38
12.0      84
13.0      71
14.0     171
15.0     185
16.0     371
17.0     836
18.0    3801
19.0    8606
Name: count, dtype: int64

In [74]:
df[age < 10][['CustomerID', 'CustomerDOB', 'CustLocation','CustAccountBalance', 'TransactionAmount (INR)']].head(20)

,CustomerID,CustomerDOB,CustLocation,CustAccountBalance,TransactionAmount (INR)
5491,C1213940,2/12/07,CHANDAULI,17728.06,11499.00
8173,C1017880,20/2/13,DELHI,20257.22,359.52
12531,C5333741,18/10/10,FARIDABAD,29225.01,500.00
12806,C1236566,3/12/11,DELHI,1109.60,120.00
13664,C6336313,20/2/13,SANPADA THANE NAVI MUMBAI,56119.22,14396.00
16353,C5733789,18/10/10,FARIDABAD,29225.01,520.00
44760,C5818512,19/4/09,NEW DELHI,954012.73,156.00
50849,C5161272,13/3/07,MOHALI,2701.05,1836.00
54681,C2461256,13/3/07,MOHALI,2701.05,1604.37
62795,C6330569,8/4/15,BHIWANDI,30609.56,816.00
74135,C6833772,18/10/10,FARIDABAD,29225.01,340.00
89820,C7638670,12/12/13,NAVI MUMBAI,42648.10,2615.67
95471,C7420834,4/10/09,MUKTSAR,3072.37,1438.00
95907,C3038673,12/12/13,NAVI MUMBAI,42648.10,700.00
114611,C2846955,22/2/16,SURAT,16205.90,460.00
116988,C7211463,2/1/07,VALSAD VAPI,15206.91,297.00
128470,C6946973,22/2/16,SURAT,16205.90,294.00
131681,C2833781,18/10/10,FARIDABAD,29225.01,600.00
141448,C1733781,18/10/10,FARIDABAD,29225.01,500.00
148139,C4736340,20/2/13,SANPADA THANE NAVI MUMBAI,56119.22,20034.00

In [76]:
df['CustomerDOB'] = dob_parsed
df['TransactionDate'] = transaction_date_parsed

In [77]:
df['CustomerAge'] = age

In [78]:
df[['CustomerDOB', 'TransactionDate', 'CustomerAge']].head(10)

  CustomerDOB TransactionDate  CustomerAge
0  1994-01-10      2016-08-02         22.0
1  1957-04-04      2016-08-02         59.0
2  1996-11-26      2016-08-02         19.0
3  1973-09-14      2016-08-02         42.0
4  1988-03-24      2016-08-02         28.0
5  1972-10-08      2016-08-02         43.0
6  1992-01-26      2016-08-02         24.0
7  1982-01-27      2016-08-02         34.0
8  1988-04-19      2016-08-02         28.0
9  1984-06-22      2016-08-02         32.0

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048567 entries, 0 to 1048566
Data columns (total 10 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   TransactionID            1048567 non-null  object
 1   CustomerID               1048567 non-null  object
 2   CustomerDOB              987831 non-null   datetime64[ns]
 3   CustGender               1047467 non-null  object
 4   CustLocation             1048416 non-null  object
 5   CustAccountBalance       1046198 non-null  float64
 6   TransactionDate          1048567 non-null  datetime64[ns]
 7   TransactionTime          1048567 non-null  int64
 8   TransactionAmount (INR)  1048567 non-null  float64
 9   CustomerAge              987831 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(1), object(4)
memory usage: 80.0+ MB

In [80]:
df['CustGender'] = df['CustGender'].replace('T', np.nan)

In [81]:
df['CustGender'].value_counts(dropna=False)

CustGender
M      765530
F      281936
NaN      1101
Name: count, dtype: int64

In [82]:
df['CustLocation'].value_counts(dropna=False).head(20)

CustLocation
MUMBAI         103595
NEW DELHI       84928
BANGALORE       81555
GURGAON         73818
DELHI           71019
NOIDA           32784
CHENNAI         30009
PUNE            25851
HYDERABAD       23049
THANE           21505
KOLKATA         19974
GHAZIABAD       15834
NAVI MUMBAI     13080
AHMEDABAD       12264
FARIDABAD       11318
JAIPUR           9921
CHANDIGARH       9526
LUCKNOW          7763
MOHALI           6741
SURAT            5770
Name: count, dtype: int64

In [83]:
df['CustLocation'].head(20)

0      JAMSHEDPUR
1         JHAJJAR
2          MUMBAI
3          MUMBAI
4     NAVI MUMBAI
5        ITANAGAR
6          MUMBAI
7          MUMBAI
8         GURGAON
9          MUMBAI
10         MOHALI
11         GUNTUR
12      AHMEDABAD
13          THANE
14           PUNE
15      NEW DELHI
16         MUMBAI
17         MUMBAI
18         MUMBAI
19           PUNE
Name: CustLocation, dtype: object

In [84]:
df['CustLocation'].str.strip().nunique()

9354

In [85]:
df['CustLocation'] = df['CustLocation'].str.strip()

In [86]:
df['CustLocation'].nunique()

9354

In [87]:
df[df['CustLocation'].isnull()].head(10)

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount (INR),CustomerAge
2256,T2257,C7383573,1990-11-01,M,NaN,262645.74,2016-10-21,204113,96.0,25.0
31269,T31270,C1433534,1973-03-09,M,NaN,2780.38,2016-09-26,124526,75.0,43.0
35568,T35569,C2737330,1986-12-10,M,NaN,17000.79,2016-09-26,190506,99.0,29.0
41588,T41589,C5833553,1973-03-09,M,NaN,2780.38,2016-08-03,92755,90.0,43.0
42840,T42841,C7233515,1973-03-09,M,NaN,2780.38,2016-08-03,93120,14.0,43.0
43998,T43999,C8233533,1973-03-09,M,NaN,2780.38,2016-08-03,93636,149.0,43.0
44832,T44833,C7912712,1994-05-18,M,NaN,8490.82,2016-08-03,83414,1465.0,22.0
45631,T45632,C5333538,1973-03-09,M,NaN,2780.38,2016-08-03,120906,233.0,43.0
45636,T45637,C4538469,1984-07-01,F,NaN,23834.28,2016-08-03,121022,1000.0,32.0
46337,T46338,C3938426,1984-07-01,F,NaN,23834.28,2016-08-03,130553,1000.0,32.0

In [88]:
(df['CustLocation'] == '').sum()

np.int64(0)

In [89]:
df[df['CustAccountBalance'].isnull()].head(10)

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount (INR),CustomerAge
29,T30,C8736958,1986-12-19,M,GRAM PANCHAYTH HYDERABAD,NaN,2016-08-03,160636,2600.00,29.0
1271,T1272,C2314972,1993-07-29,M,THANE,NaN,2016-10-21,203227,53.00,23.0
2513,T2514,C3742855,1987-03-18,F,MUMBAI,NaN,2016-10-21,150602,300.00,29.0
2831,T2832,C3221342,2002-02-27,M,NEW DELHI,NaN,2016-10-21,54746,1.00,14.0
3550,T3551,C5921379,2002-02-27,M,NEW DELHI,NaN,2016-10-21,54704,1.00,14.0
3703,T3704,C2821380,2002-02-27,M,NEW DELHI,NaN,2016-10-21,114700,50.00,14.0
3854,T3855,C4421928,1987-09-16,F,NOIDA,NaN,2016-09-22,143740,247.00,29.0
4708,T4709,C8886977,1990-06-01,M,MUMBAI,NaN,2016-08-16,105227,200.00,26.0
7600,T7601,C6612383,1994-09-12,M,DELHI,NaN,2016-09-25,195332,1577.00,22.0
7851,T7852,C7935712,1991-06-09,M,DELHI,NaN,2016-09-25,185519,1190.45,25.0

In [90]:
(df['CustAccountBalance'] < 0).sum()

np.int64(0)

In [91]:
(df['CustAccountBalance'] == 0).sum()

np.int64(2711)

In [92]:
df.nlargest(10, 'CustAccountBalance')[['CustomerID', 'CustLocation', 'CustAccountBalance', 'TransactionAmount (INR)']]

        CustomerID CustLocation  CustAccountBalance  TransactionAmount (INR)
40982     C2916865     SHILLONG         115035495.1                  6959.00
656264    C3316830     SHILLONG         115035495.1                 28019.32
789085    C6416825     SHILLONG         115035495.1                  5864.00
826721    C2216823     SHILLONG         115035495.1                  4699.00
835641    C2916887     SHILLONG         115035495.1                   600.00
876392    C8116818     SHILLONG         115035495.1                  3149.00
879623    C4316889     SHILLONG         115035495.1                  4364.00
1001213   C5916881     SHILLONG         115035495.1                  1599.00
1002072   C5116828     SHILLONG         115035495.1                  5060.00
1002847   C7716886     SHILLONG         115035495.1                  3604.00

In [93]:
df[df['CustAccountBalance'] == df['CustAccountBalance'].max()].shape

(10, 10)

In [97]:
df[df['CustAccountBalance'] == df['CustAccountBalance'].max()][['CustomerID', 'CustLocation', 'CustAccountBalance']].head(20)

        CustomerID CustLocation  CustAccountBalance
40982     C2916865     SHILLONG         115035495.1
656264    C3316830     SHILLONG         115035495.1
789085    C6416825     SHILLONG         115035495.1
826721    C2216823     SHILLONG         115035495.1
835641    C2916887     SHILLONG         115035495.1
876392    C8116818     SHILLONG         115035495.1
879623    C4316889     SHILLONG         115035495.1
1001213   C5916881     SHILLONG         115035495.1
1002072   C5116828     SHILLONG         115035495.1
1002847   C7716886     SHILLONG         115035495.1

In [98]:
df[df['CustAccountBalance'] == df['CustAccountBalance'].max()]['CustomerID'].nunique()

10

In [108]:
missing_balance = df[df['CustAccountBalance'].isnull()]
missing_balance

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount (INR),CustomerAge
29,T30,C8736958,1986-12-19,M,GRAM PANCHAYTH HYDERABAD,NaN,2016-08-03,160636,2600.0,29.0
1271,T1272,C2314972,1993-07-29,M,THANE,NaN,2016-10-21,203227,53.0,23.0
2513,T2514,C3742855,1987-03-18,F,MUMBAI,NaN,2016-10-21,150602,300.0,29.0
2831,T2832,C3221342,2002-02-27,M,NEW DELHI,NaN,2016-10-21,54746,1.0,14.0
3550,T3551,C5921379,2002-02-27,M,NEW DELHI,NaN,2016-10-21,54704,1.0,14.0
...,...,...,...,...,...,...,...,...,...,...
1045875,T1045876,C4427246,1980-04-25,M,SALEM,NaN,2016-09-18,131053,2363.0,36.0
1046193,T1046194,C4813286,1995-11-29,F,INDORE,NaN,2016-09-18,20752,326.0,20.0
1046726,T1046727,C1035768,1991-06-09,M,DELHI,NaN,2016-09-18,200816,7500.0,25.0
1046825,T1046826,C6231941,1983-08-08,F,NAVI MUMBAI,NaN,2016-09-18,190130,9092.0,33.0
1048048,T1048049,C1927213,1980-04-25,M,SALEM,NaN,2016-09-18,82422,2200.0,36.0

In [100]:
missing_balance['CustomerID'].nunique()

2366

In [106]:
missing_customer_ids = missing_balance['CustomerID'].unique()
missing_customer_ids

array(['C8736958', 'C2314972', 'C3742855', ..., 'C1035768', 'C6231941',
       'C1927213'], dtype=object)

In [109]:
df[df['CustomerID'].isin(missing_customer_ids)]['CustAccountBalance'].notnull().sum()

np.int64(865)

In [110]:
df[
    df['CustomerID'].isin(missing_customer_ids)
    & df['CustAccountBalance'].notnull()
]['CustomerID'].nunique()

701

In [111]:
(df['TransactionAmount (INR)'] < 0).sum()

np.int64(0)

In [112]:
(df['TransactionAmount (INR)'] == 0).sum()

np.int64(835)

In [113]:
df['TransactionAmount (INR)'].describe()

count    1.048567e+06
mean     1.574335e+03
std      6.574743e+03
min      0.000000e+00
25%      1.610000e+02
50%      4.590300e+02
75%      1.200000e+03
max      1.560035e+06
Name: TransactionAmount (INR), dtype: float64

In [114]:
df.nlargest(10, 'TransactionAmount (INR)')[
    ['CustomerID', 'CustLocation', 'CustAccountBalance',
     'TransactionAmount (INR)', 'TransactionDate']
]

,CustomerID,CustLocation,CustAccountBalance,TransactionAmount (INR),TransactionDate
399117,C7319271,GURGAON,42487.89,1560034.99,2016-08-18
579014,C6677159,PUNE,98660.33,1380002.88,2016-08-22
532036,C4141768,NEW DELHI,83608.10,991132.22,2016-08-23
749353,C8217728,MUMBAI,61382213.47,724122.00,2016-09-02
56540,C1830891,KOLKATA,14177.65,720001.16,2016-08-03
846924,C6549785,NOIDA,29198.46,600008.32,2016-09-09
173291,C5036642,NEW DELHI,136294.60,600003.45,2016-08-04
356306,C4328064,DELHI,38735.17,569500.27,2016-08-14
152735,C1425138,MUMBAI,9324.35,561001.00,2016-08-05
403383,C5833636,PALAKKARAI TRICHY,143883.69,557000.73,2016-08-18

In [115]:
df['TransactionTime'].head(20)

0     143207
1     141858
2     142712
3     142714
4     181156
5     173940
6     173806
7     170537
8     192825
9     192446
10    204133
11    205108
12    203834
13     84706
14     82253
15    125725
16    124727
17    124734
18    122135
19    152821
Name: TransactionTime, dtype: int64

In [116]:
df['TransactionTime'].min(), df['TransactionTime'].max()

(0, 235959)

In [121]:
df['TransactionTime'].astype(str).str.len().value_counts().sort_index()

TransactionTime
1        61
2       320
3      3498
4     14098
5    108472
6    922118
Name: count, dtype: int64

In [139]:
time_str = df['TransactionTime'].astype(str).str.zfill(6)

In [132]:
hours = time_str.str[:2].astype(int)
minutes = time_str.str[2:4].astype(int)
seconds = time_str.str[4:6].astype(int)

In [135]:
(hours > 23).sum()
(minutes > 59).sum()
(seconds > 59).sum()

np.int64(0)

In [136]:
print((hours > 23).sum())
print((minutes > 59).sum())
print((seconds > 59).sum())

0
0
0

In [140]:
transaction_time_parsed = pd.to_datetime(
    time_str,
    format='%H%M%S',
    errors='coerce'
).dt.time

In [141]:
transaction_time_parsed.head(20)

0     14:32:07
1     14:18:58
2     14:27:12
3     14:27:14
4     18:11:56
5     17:39:40
6     17:38:06
7     17:05:37
8     19:28:25
9     19:24:46
10    20:41:33
11    20:51:08
12    20:38:34
13    08:47:06
14    08:22:53
15    12:57:25
16    12:47:27
17    12:47:34
18    12:21:35
19    15:28:21
Name: TransactionTime, dtype: object

In [142]:
transaction_time_parsed.isnull().sum()

np.int64(0)

In [143]:
df['TransactionTime'] = transaction_time_parsed

In [144]:
df['TransactionHour'] = hours

In [145]:
df[['TransactionTime', 'TransactionHour']].head(10)

  TransactionTime  TransactionHour
0        14:32:07               14
1        14:18:58               14
2        14:27:12               14
3        14:27:14               14
4        18:11:56               18
5        17:39:40               17
6        17:38:06               17
7        17:05:37               17
8        19:28:25               19
9        19:24:46               19

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048567 entries, 0 to 1048566
Data columns (total 11 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   TransactionID            1048567 non-null  object
 1   CustomerID               1048567 non-null  object
 2   CustomerDOB              987831 non-null   datetime64[ns]
 3   CustGender               1047466 non-null  object
 4   CustLocation             1048416 non-null  object
 5   CustAccountBalance       1046198 non-null  float64
 6   TransactionDate          1048567 non-null  datetime64[ns]
 7   TransactionTime          1048567 non-null  object
 8   TransactionAmount (INR)  1048567 non-null  float64
 9   CustomerAge              987831 non-null   float64
 10  TransactionHour          1048567 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(1), object(5)
memory usage: 88.0+ MB

In [147]:
df['TransactionID'].duplicated().sum()

np.int64(0)

In [148]:
df.duplicated().sum()

np.int64(0)

In [149]:
df.isnull().sum()

TransactionID                  0
CustomerID                     0
CustomerDOB                60736
CustGender                  1101
CustLocation                 151
CustAccountBalance          2369
TransactionDate                0
TransactionTime                0
TransactionAmount (INR)        0
CustomerAge                60736
TransactionHour                0
dtype: int64

In [150]:
bins = [0, 18, 25, 35, 45, 55, 65, float('inf')]

In [151]:
labels = [
    'Under 18',
    '18-24',
    '25-34',
    '35-44',
    '45-54',
    '55-64',
    '65+'
]

In [152]:
df['AgeGroup'] = pd.cut(
    df['CustomerAge'],
    bins=bins,
    labels=labels,
    right=False
)

In [154]:
df[['CustomerAge', 'AgeGroup']].head(20)

    CustomerAge AgeGroup
0          22.0    18-24
1          59.0    55-64
2          19.0    18-24
3          42.0    35-44
4          28.0    25-34
5          43.0    35-44
6          24.0    18-24
7          34.0    25-34
8          28.0    25-34
9          32.0    25-34
10         34.0    25-34
11         28.0    25-34
12         38.0    35-44
13         24.0    18-24
14         38.0    35-44
15         48.0    45-54
16          NaN      NaN
17         27.0    25-34
18         25.0    25-34
19         31.0    25-34

In [155]:
df['AgeGroup'].value_counts(dropna=False).sort_index()

AgeGroup
Under 18      1980
18-24       222063
25-34       529526
35-44       161577
45-54        47123
55-64        17579
65+           7983
NaN          60736
Name: count, dtype: int64

In [156]:
def get_time_of_day(hour):
    if 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

In [157]:
df['TimeOfDay'] = df['TransactionHour'].apply(get_time_of_day)

In [158]:
df[['TransactionTime', 'TransactionHour', 'TimeOfDay']].head(20)

   TransactionTime  TransactionHour  TimeOfDay
0         14:32:07               14  Afternoon
1         14:18:58               14  Afternoon
2         14:27:12               14  Afternoon
3         14:27:14               14  Afternoon
4         18:11:56               18    Evening
5         17:39:40               17    Evening
6         17:38:06               17    Evening
7         17:05:37               17    Evening
8         19:28:25               19    Evening
9         19:24:46               19    Evening
10        20:41:33               20    Evening
11        20:51:08               20    Evening
12        20:38:34               20    Evening
13        08:47:06                8    Morning
14        08:22:53                8    Morning
15        12:57:25               12  Afternoon
16        12:47:27               12  Afternoon
17        12:47:34               12  Afternoon
18        12:21:35               12  Afternoon
19        15:28:21               15  Afternoon

In [159]:
df['TimeOfDay'].value_counts()

TimeOfDay
Evening      340003
Afternoon    321662
Night        212429
Morning      174473
Name: count, dtype: int64

In [160]:
df['TransactionMonth'] = df['TransactionDate'].dt.month

In [161]:
df['TransactionMonthName'] = df['TransactionDate'].dt.month_name()

In [162]:
df[['TransactionDate', 'TransactionMonth', 'TransactionMonthName']].head(10)

  TransactionDate  TransactionMonth TransactionMonthName
0      2016-08-02                 8               August
1      2016-08-02                 8               August
2      2016-08-02                 8               August
3      2016-08-02                 8               August
4      2016-08-02                 8               August
5      2016-08-02                 8               August
6      2016-08-02                 8               August
7      2016-08-02                 8               August
8      2016-08-02                 8               August
9      2016-08-02                 8               August

In [163]:
df['TransactionMonthName'].value_counts()

TransactionMonthName
August       653933
September    390975
October        3659
Name: count, dtype: int64

In [164]:
df['TransactionDay'] = df['TransactionDate'].dt.day_name()

In [165]:
df[['TransactionDate', 'TransactionDay']].head(10)

  TransactionDate TransactionDay
0      2016-08-02        Tuesday
1      2016-08-02        Tuesday
2      2016-08-02        Tuesday
3      2016-08-02        Tuesday
4      2016-08-02        Tuesday
5      2016-08-02        Tuesday
6      2016-08-02        Tuesday
7      2016-08-02        Tuesday
8      2016-08-02        Tuesday
9      2016-08-02        Tuesday

In [166]:
df['TransactionDay'].value_counts()

TransactionDay
Sunday       171771
Monday       155525
Thursday     151331
Saturday     148506
Tuesday      145677
Wednesday    142252
Friday       133505
Name: count, dtype: int64

In [172]:
amount_bins = [-0.01, 0.01, 500, 1000, 5000, 10000, 50000, float('inf')]

amount_labels = [
    'Zero Amount',
    'Below 500',
    '500-999',
    '1K-4.9K',
    '5K-9.9K',
    '10K-49.9K',
    '50K+'
]

In [173]:
df['TransactionAmountBand'] = pd.cut(
    df['TransactionAmount (INR)'],
    bins=amount_bins,
    labels=amount_labels,
    right=False
)

In [174]:
df[['TransactionAmount (INR)', 'TransactionAmountBand']].head(20)

    TransactionAmount (INR) TransactionAmountBand
0                     25.00             Below 500
1                  27999.00             10K-49.9K
2                    459.00             Below 500
3                   2060.00               1K-4.9K
4                   1762.50               1K-4.9K
5                    676.00               500-999
6                    566.00               500-999
7                    148.00             Below 500
8                    833.00               500-999
9                    289.11             Below 500
10                   259.00             Below 500
11                   202.00             Below 500
12                 12300.00             10K-49.9K
13                    50.00             Below 500
14                   338.00             Below 500
15                   250.00             Below 500
16                  1423.11               1K-4.9K
17                    54.00             Below 500
18                   315.00             Below 500
19                   945.00               500-999

In [175]:
df['TransactionAmountBand'].value_counts().sort_index()

TransactionAmountBand
Zero Amount       835
Below 500      541308
500-999        185996
1K-4.9K        262969
5K-9.9K         32017
10K-49.9K       22578
50K+             2864
Name: count, dtype: int64

In [176]:
df['CustAccountBalance'].describe(percentiles=[0.25, 0.5, 0.75, 0.90, 0.95, 0.99])

count    1.046198e+06
mean     1.154035e+05
std      8.464854e+05
min      0.000000e+00
25%      4.721760e+03
50%      1.679218e+04
75%      5.765736e+04
90%      1.985042e+05
95%      4.161645e+05
99%      1.586901e+06
max      1.150355e+08
Name: CustAccountBalance, dtype: float64

In [178]:
balance_bins = [-0.01, 5000, 25000, 50000, 100000, 500000, float('inf')]

balance_labels = [
    'Below 5K',
    '5K-24.9K',
    '25K-49.9K',
    '50K-99.9K',
    '1L-4.9L',
    '5L+'
]

In [179]:
df['AccountBalanceBand'] = pd.cut(
    df['CustAccountBalance'],
    bins=balance_bins,
    labels=balance_labels,
    right=False
)

In [180]:
df[['CustAccountBalance', 'AccountBalanceBand']].head(20)

    CustAccountBalance AccountBalanceBand
0             17819.05           5K-24.9K
1              2270.69           Below 5K
2             17874.44           5K-24.9K
3            866503.21                5L+
4              6714.43           5K-24.9K
5             53609.20          50K-99.9K
6               973.46           Below 5K
7             95075.54          50K-99.9K
8             14906.96           5K-24.9K
9              4279.22           Below 5K
10            48429.49          25K-49.9K
11            14613.46           5K-24.9K
12            32274.78          25K-49.9K
13            59950.44          50K-99.9K
14            10100.84           5K-24.9K
15             1283.12           Below 5K
16            77495.15          50K-99.9K
17             2177.85           Below 5K
18            32816.17          25K-49.9K
19            10643.50           5K-24.9K

In [181]:
df['AccountBalanceBand'].value_counts(dropna=False).sort_index()

AccountBalanceBand
Below 5K     270019
5K-24.9K     345312
25K-49.9K    144273
50K-99.9K    107583
1L-4.9L      136515
5L+           42496
NaN            2369
Name: count, dtype: int64

In [182]:
df.shape

(1048567, 18)

In [183]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048567 entries, 0 to 1048566
Data columns (total 18 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   TransactionID            1048567 non-null  object
 1   CustomerID               1048567 non-null  object
 2   CustomerDOB              987831 non-null   datetime64[ns]
 3   CustGender               1047466 non-null  object
 4   CustLocation             1048416 non-null  object
 5   CustAccountBalance       1046198 non-null  float64
 6   TransactionDate          1048567 non-null  datetime64[ns]
 7   TransactionTime          1048567 non-null  object
 8   TransactionAmount (INR)  1048567 non-null  float64
 9   CustomerAge              987831 non-null   float64
 10  TransactionHour          1048567 non-null  int64
 11  AgeGroup                 987831 non-null   category
 12  TimeOfDay                1048567 non-null  object
 13  TransactionMonth         1048567 non-null  int32
 14  TransactionMonthName     1048567 non-null  object
 15  TransactionDay           1048567 non-null  object
 16  TransactionAmountBand    1048567 non-null  category
 17  AccountBalanceBand       1046198 non-null  category
dtypes: category(3), datetime64[ns](2), float64(3), int32(1), int64(1), object(8)
memory usage: 119.0+ MB

In [184]:
df.head()

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount (INR),CustomerAge,TransactionHour,AgeGroup,TimeOfDay,TransactionMonth,TransactionMonthName,TransactionDay,TransactionAmountBand,AccountBalanceBand
0,T1,C5841053,1994-01-10,F,JAMSHEDPUR,17819.05,2016-08-02,14:32:07,25.0,22.0,14,18-24,Afternoon,8,August,Tuesday,Below 500,5K-24.9K
1,T2,C2142763,1957-04-04,M,JHAJJAR,2270.69,2016-08-02,14:18:58,27999.0,59.0,14,55-64,Afternoon,8,August,Tuesday,10K-49.9K,Below 5K
2,T3,C4417068,1996-11-26,F,MUMBAI,17874.44,2016-08-02,14:27:12,459.0,19.0,14,18-24,Afternoon,8,August,Tuesday,Below 500,5K-24.9K
3,T4,C5342380,1973-09-14,F,MUMBAI,866503.21,2016-08-02,14:27:14,2060.0,42.0,14,35-44,Afternoon,8,August,Tuesday,1K-4.9K,5L+
4,T5,C9031234,1988-03-24,F,NAVI MUMBAI,6714.43,2016-08-02,18:11:56,1762.5,28.0,18,25-34,Evening,8,August,Tuesday,1K-4.9K,5K-24.9K

In [185]:
df.isnull().sum()

TransactionID                  0
CustomerID                     0
CustomerDOB                60736
CustGender                  1101
CustLocation                 151
CustAccountBalance          2369
TransactionDate                0
TransactionTime                0
TransactionAmount (INR)        0
CustomerAge                60736
TransactionHour                0
AgeGroup                   60736
TimeOfDay                      0
TransactionMonth               0
TransactionMonthName           0
TransactionDay                 0
TransactionAmountBand          0
AccountBalanceBand          2369
dtype: int64

In [186]:
df.to_csv(
    '../data/processed/bank_transactions_cleaned.csv',
    index=False
)

In [187]:
import os

os.path.exists('../data/processed/bank_transactions_cleaned.csv')

True